### Configuration for Allimore Quest
## Possible Colors:
## Black, Dark_Blue, Dark_Green, Dark_Aqua, Dark_Red, Dark_Purple, Gold, Gray, Dark_Gray, Blue, Green, Aqua, Red, Light_Purple, Yellow, White

## Settings for Chat Notifications
Chat Notifications:
    Title Color: Gold
    Summary Color: Yellow
    Objective Color: Red
    Abandon Quest Color: Red
    Complete Quest Color: Green

## Settings for Sound Notifications
Sound Notifications:
  Quest Start:
    Clip: Entity_Arrow_Hit_Player
    Volume: 1
    Pitch: .5
  Quest Complete:
    Clip: Entity_Player_LevelUp
    Volume: 1
    Pitch: 1.3
  Quest Abandon:
    Clip: Entity_Arrow_Hit_Player
    Volume: 1
    Pitch: .5

## Settings for Title Based Notifications
Title Notifications:
  Title Color: Green
  Subtitle Color: White
  Quest Notification Fade In: 10
  Quest Notification Stay: 20
  Quest Notification Fade Out: 10

## Settings for Player Data
Player Data:
  Auto Save Interval: 30
  Player Data Unload Delay: 5